create table flights
(
    year integer,
    month integer,
    day integer,
    day_of_week integer,
    airline text,
    flight_number integer,
    tail_number text,
    origin_airport char(3),
    destination_airport char(3),
    scheduled_departure integer,
    departure_time integer,
    departure_delay integer,
    taxi_out integer,
    wheels_off integer,
    scheduled_time integer,
    elapsed_time integer,
    air_time integer,
    distance integer,
    wheels_on integer,
    taxi_in integer,
    scheduled_arrival integer,
    arrival_time integer,
    arrival_delay integer,
    diverted integer,
    cancelled integer,
    cancellation_reason text,
    air_system_delay integer,
    security_delay integer,
    airline_delay integer,
    late_aircraft_delay integer,
    weather_delay integer
);